### ISSUE TITLE
请教一下，我想把东西实时弄出来然后送到Radeon ProRender里，您这项目能实现吗？

### ISSUE THREAD

**Issue by zhouhang95** [MoePus/mmdhook#1]

**Comment by MoePus** [comment]
这个项目里面功能基本都没有实现，所以恐怕不行。
你可以关注一下MMDBridge这个项目，可以试试通过Hook他的给optix的接口让你amd用

**Comment by zhouhang95** [comment]
这个Radeon ProRender库是64位的 而mmd是32位的能连上吗
